[package]
name = "d2rhub"
version = "0.8.0"
description = "Diablo II Resurrected Multi-Account Manager"
authors = ["D2RHub"]
edition = "2021"
license = "MIT"
repository = "https://github.com/gjy991229/D2RHub"
homepage = "https://github.com/gjy991229/D2RHub"
readme = "../README.md"

[lib]
name = "d2rhub_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[[bin]]
name = "d2rhub"
path = "src/main.rs"
test = false
doctest = false

[build-dependencies]
tauri-build = { version = "2", features = [] }

[features]
default = ["rune-audio"]
stats = ["dep:rusqlite", "dep:open"]
rune-audio = ["stats", "dep:claxon", "dep:flacenc", "dep:wasapi", "dep:casc-core", "dep:hound"]

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-shell = "2"
tauri-plugin-dialog = "2"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
uuid = { version = "1", features = ["v4"] }
parking_lot = "0.12"
sysinfo = "0.31"
dirs = "5"
chrono = { version = "0.4", features = ["serde"] }
tokio = { version = "1", features = ["time"] }
windows = { version = "0.58", features = ["Foundation", "Win32_Security_Cryptography"] }
winreg = "0.52"
# 数据统计 SQLite
rusqlite = { version = "0.31", features = ["bundled"], optional = true }
open = { version = "5", optional = true }
claxon = { version = "0.4.3", optional = true }
flacenc = { version = "0.5.1", default-features = false, optional = true }
casc-core = { git = "https://github.com/TrayHard/casc-modern.git", rev = "a7fe4095f4ce445b9135b26509c5f60ae63d8c21", optional = true }
hound = { version = "3.5.1", optional = true }
reqwest = { version = "0.12", features = ["stream", "rustls-tls"], default-features = false }

[target.'cfg(windows)'.dependencies]
wasapi = { version = "0.24.0", optional = true }
