import type { SettingsLanguage } from "../settings/settingsRegistry";

export const ROOM_AUTOMATION_COPY = {
  "zh-CN": {
    title: "自动跟房",
    subtitle: "主账号建房，跟随账号按设定加入；全程只发送键盘输入。",
    enabled: "启用自动跟房模块",
    unavailable: "模块不可用",
    loading: "正在读取模块状态…",
    disabled: "模块已停用",
    disabledDescription: "配置会保留，但快捷键、文件监视和跟房任务均不会运行。",
    ready: "模块已就绪",
    error: "任务需要处理",
    apply: "应用配置",
    applying: "正在应用",
    discard: "放弃更改",
    applied: "配置已应用",
    unsaved: "有未应用的更改",
    unsavedHelp: "只有点击“应用配置”后，快捷键、监听器和运行参数才会更新。",
    staleHint: "配置已被其他操作更新，请重新载入后再应用。",
    retryLoad: "重新载入",
    participants: "参与账号",
    participantsHelp: "主账号负责创建房间；跟随账号将在第二阶段加入同一房间。",
    enablePromptTitle: "启用自动跟房",
    enablePromptDescription: "参与账号需要使用包含“局内房间工具”的 D2RHub 加工 Mod。你可以先去检查或加工 Mod，也可以在已经确认准备完成后继续启用。",
    checkModFirst: "先检查 Mod",
    continueEnable: "已准备好，继续启用",
    modRedirectHint: "请为参与账号确认或加工“局内房间工具”，完成后再返回启用自动跟房。",
    primary: "主账号",
    selectPrimary: "选择主账号",
    followers: "跟随账号",
    noAccounts: "没有可用的已初始化账号。请先在“账号与实例”完成初始化。",
    modeAndRoom: "运行方式与房间",
    manualMode: "手动跟随",
    manualModeHelp: "主账号创建成功后暂停，确认后再让其他账号加入。",
    automaticMode: "自动跟随",
    automaticModeHelp: "主账号创建成功后，等待指定秒数并自动让其他账号加入。",
    followerDelay: "自动跟随等待（秒）",
    createShortcut: "创建房间快捷键",
    followerShortcut: "跟随账号快捷键",
    shortcutCapture: "点击后按下组合键",
    shortcutRecording: "请按下组合键…",
    prefix: "房名开头",
    password: "房间密码",
    sequence: "下一个序号",
    width: "序号位数",
    preview: "下次房名",
    workflow: "本次任务",
    startPrimary: "主账号创建房间",
    nextPrimary: "下一序号重新建房",
    startFollowers: "让跟随账号加入",
    retry: "重试当前房间",
    retryPrimary: "重试建房（下一序号）",
    retryFollowers: "重试跟随（同一房间）",
    cancel: "取消任务",
    phase: {
      idle: "等待开始",
      primary: "主账号操作中",
      waiting: "等待跟随账号",
      followers: "跟随账号加入中",
      complete: "任务已完成",
      cancelled: "任务已取消",
      error: "任务失败",
    },
    room: "房间",
    attempt: "尝试次数",
    followerProgress: "跟随进度",
    waitAutomatic: (seconds: number) => `${seconds} 秒后自动继续`,
    waitManual: "等待你确认：可让跟随账号加入；若房名重复，可用下一序号重新建房",
    f13Title: "游戏聊天键绑定",
    f13Description: "跟房需要 F13 打开聊天输入。安装时只修改角色按键文件中的第二个“聊天”槽位，并创建可恢复备份。",
    f13Consent: "点击安装即表示你明确授权 D2RHub 修改兼容的角色按键文件，并在模块启用期间监视新文件。",
    f13LegacyNotice: "旧版配置中的自动授权已被撤销。请阅读说明后重新确认。",
    bindingReady: "F13 绑定已就绪",
    bindingNotReady: "F13 绑定尚未就绪",
    bindingUnavailable: "无法读取 F13 绑定状态",
    bindingLoading: "正在读取 F13 绑定状态…",
    retryBinding: "重试读取",
    refreshBinding: "刷新状态",
    bindingRequired: "请先完成 F13 聊天键绑定",
    bindingFiles: (installed: number, total: number) => `${installed}/${total} 个按键文件已安装`,
    bindingConflicts: (count: number) => `${count} 个文件存在按键冲突，未自动修改`,
    bindingOrphans: (count: number) => `保留 ${count} 个已删除角色的历史备份，不影响当前角色`,
    watcherActive: "自动补齐监视中",
    gameMustClose: "请先关闭所有 D2R 进程，再安装或恢复按键文件。",
    installBinding: "授权并安装 F13 绑定",
    restoreBinding: "恢复原始按键绑定",
    advanced: "高级输入时序",
    advancedHelp: "只有在机器负载较高或游戏大厅响应异常时才需要调整。",
    stepDelay: "步骤间隔（毫秒）",
    characterDelay: "字符间隔（毫秒）",
    backgroundStrategy: "后台文本投递",
    postKeys: "Windows 消息投递（推荐）",
    sendKeys: "前台按键投递",
    primaryRequired: "启用前请选择主账号。",
    followersRequired: "启用前至少选择一个跟随账号。",
    duplicateParticipants: "同一账号不能同时作为主账号和跟随账号。",
    shortcutRequired: "启用前请设置两个快捷键。",
    shortcutInvalid: "快捷键格式无效；请点击输入框并直接按下组合键。",
    shortcutConflict: "创建和跟随快捷键不能相同。",
    invalidRoomText: "仅支持英文字母、数字、连字符和下划线。",
    roomTooLong: "房名和密码最多 15 个字符。",
    invalidSequence: "序号必须是 0–4294967295 的整数，位数应为 1–6。",
    invalidTiming: "自动等待应为 2–60 秒；步骤间隔 0–2000 毫秒，字符间隔 10–250 毫秒。",
    accountUnavailable: "配置中包含已删除或尚未初始化的账号，请重新选择。",
    loadFailed: "无法读取自动跟房模块",
    saveFailed: "无法应用自动跟房配置",
    savedButRuntimeFailed: "配置已保存，但模块未能立即应用",
    actionFailed: "自动跟房操作失败",
    bindingFailed: "无法更新 F13 按键绑定",
  },
  "en-US": {
    title: "Room Automation",
    subtitle: "The primary creates; followers join as configured. Every action stays keyboard-only.",
    enabled: "Enable room automation",
    unavailable: "Module unavailable",
    loading: "Loading module status…",
    disabled: "Module off",
    disabledDescription: "Your configuration is kept, but shortcuts, file watching, and room tasks do not run.",
    ready: "Module ready",
    error: "Task needs attention",
    apply: "Apply settings",
    applying: "Applying",
    discard: "Discard",
    applied: "Settings applied",
    unsaved: "Unapplied changes",
    unsavedHelp: "Shortcuts, watchers, and runtime settings change only after you select Apply settings.",
    staleHint: "Settings changed elsewhere. Reload before applying again.",
    retryLoad: "Reload",
    participants: "Participants",
    participantsHelp: "The primary creates the room; followers join it in the second stage.",
    enablePromptTitle: "Enable room automation",
    enablePromptDescription: "Every participant needs a D2RHub-processed Mod containing In-game room tools. Check or process the Mods first, or continue if you have already verified them.",
    checkModFirst: "Check Mods first",
    continueEnable: "Already ready — enable",
    modRedirectHint: "Verify or add In-game room tools for each participant, then return to enable room automation.",
    primary: "Primary account",
    selectPrimary: "Select a primary account",
    followers: "Follower accounts",
    noAccounts: "No initialized accounts are available. Finish setup in Accounts & Instances first.",
    modeAndRoom: "Mode & room",
    manualMode: "Manual followers",
    manualModeHelp: "Pause after the primary creates the room, then join followers when you confirm.",
    automaticMode: "Automatic followers",
    automaticModeHelp: "Wait for the chosen delay after creation, then join followers automatically.",
    followerDelay: "Follower delay (seconds)",
    createShortcut: "Create-room shortcut",
    followerShortcut: "Join-followers shortcut",
    shortcutCapture: "Click, then press a key combination",
    shortcutRecording: "Press a key combination…",
    prefix: "Room prefix",
    password: "Room password",
    sequence: "Next sequence",
    width: "Sequence width",
    preview: "Next room",
    workflow: "Current task",
    startPrimary: "Create with primary",
    nextPrimary: "Recreate with next sequence",
    startFollowers: "Join followers",
    retry: "Retry this room",
    retryPrimary: "Retry creation (next sequence)",
    retryFollowers: "Retry followers (same room)",
    cancel: "Cancel task",
    phase: {
      idle: "Ready to start",
      primary: "Primary in progress",
      waiting: "Waiting for followers",
      followers: "Followers joining",
      complete: "Task complete",
      cancelled: "Task cancelled",
      error: "Task failed",
    },
    room: "Room",
    attempt: "Attempts",
    followerProgress: "Follower progress",
    waitAutomatic: (seconds: number) => `Continuing automatically in ${seconds}s`,
    waitManual: "Choose whether to join followers or recreate with the next sequence",
    f13Title: "In-game chat binding",
    f13Description: "Room automation uses F13 to open chat input. Installation changes only the second Chat slot in character key files and creates restorable backups.",
    f13Consent: "By installing, you explicitly authorize D2RHub to update eligible character key files and watch new files while the module is enabled.",
    f13LegacyNotice: "Implicit authorization from an older configuration was revoked. Review this notice and consent again.",
    bindingReady: "F13 binding ready",
    bindingNotReady: "F13 binding not ready",
    bindingUnavailable: "Could not read the F13 binding status",
    bindingLoading: "Loading F13 binding status…",
    retryBinding: "Retry status",
    refreshBinding: "Refresh status",
    bindingRequired: "Set up the F13 chat binding first",
    bindingFiles: (installed: number, total: number) => `${installed}/${total} key files installed`,
    bindingConflicts: (count: number) => `${count} files have key conflicts and were not changed`,
    bindingOrphans: (count: number) => `${count} backups for removed characters are retained and do not block current characters`,
    watcherActive: "Auto-patch watching",
    gameMustClose: "Close every D2R process before installing or restoring key files.",
    installBinding: "Authorize & install F13",
    restoreBinding: "Restore original binding",
    advanced: "Advanced input timing",
    advancedHelp: "Adjust only when a heavily loaded machine or game lobby responds unreliably.",
    stepDelay: "Step delay (ms)",
    characterDelay: "Character delay (ms)",
    backgroundStrategy: "Background text delivery",
    postKeys: "Windows message delivery (recommended)",
    sendKeys: "Foreground key delivery",
    primaryRequired: "Choose a primary account before enabling.",
    followersRequired: "Choose at least one follower before enabling.",
    duplicateParticipants: "An account cannot be both primary and follower.",
    shortcutRequired: "Set both shortcuts before enabling.",
    shortcutInvalid: "Invalid shortcut. Click the field and press the combination directly.",
    shortcutConflict: "Create and follower shortcuts must differ.",
    invalidRoomText: "Use letters, numbers, hyphens, and underscores only.",
    roomTooLong: "Room names and passwords are limited to 15 characters.",
    invalidSequence: "Sequence must be an integer from 0 to 4294967295; width must be 1–6.",
    invalidTiming: "Auto delay is 2–60s; step delay 0–2000ms; character delay 10–250ms.",
    accountUnavailable: "The configuration references a deleted or uninitialized account. Select accounts again.",
    loadFailed: "Could not load room automation",
    saveFailed: "Could not apply room automation settings",
    savedButRuntimeFailed: "Settings were saved, but the module could not apply them immediately",
    actionFailed: "Room automation action failed",
    bindingFailed: "Could not update the F13 binding",
  },
} as const satisfies Record<SettingsLanguage, object>;
