import type { SettingsLanguage } from "../settings/settingsRegistry";

export const ROOM_AUTOMATION_COPY = {
  "zh-CN": {
    enableLabel: "启用",
    saveLaunchScheme: "保存启动方案",
    retrySave: "重试保存",
    followTrigger: "跟随触发",
    selectAllFollowers: "全选",
    clearFollowers: "清空",
    followersSelected: (count: number) => `已选 ${count} 个`,
    followerOrder: "进房顺序",
    backgroundMethodHelp: "创建时主号保持前台，所有账号同时呼出表单，配合前台 Ctrl 全选并粘贴房名。密码首次填写、变化或有新进程时整组更新。主号先创建，小号保持表单；手动按跟随快捷键或自动等待后，仅投递回车。填写期间短暂接管键鼠和剪贴板。",
    title: "自动跟房",
    subtitle: "设置主号、跟随账号和房名规则；修改会自动保存。",
    enabled: "启用自动跟房模块",
    unavailable: "模块不可用",
    loading: "正在读取模块状态…",
    disabled: "模块已停用",
    disabledDescription: "配置会保留，但快捷键和跟房任务均不会运行。",
    ready: "模块已就绪",
    error: "任务需要处理",
    apply: "应用配置",
    applying: "正在保存…",
    discard: "放弃更改",
    applied: "配置已应用",
    unsaved: "有未保存的修改",
    unsavedHelp: "有效修改会自动保存；校验未通过的内容会保留在本页，不会更新运行参数。",
    staleHint: "配置已被其他操作更新，请重新载入后再应用。",
    retryLoad: "重新载入",
    participants: "参与账号",
    participantsHelp: "指定创建者与需要加入同一房间的账号。",
    participantCapsules: "参与账号 Mod",
    participantCapsulesHelp: "主号和小号分别选择需要使用的 Mod；缺少房间工具时会引导加工。",
    selectCapsule: "选择 Mod",
    prepareCapsule: "前往加工",
    capsuleReady: "局内房间工具已就绪",
    capsuleMissing: "缺少可用的局内房间工具",
    capsulePoolLoading: "正在读取可用 Mod，请稍候。",
    capsulePoolUnavailable: "无法读取可用 Mod 列表",
    capsuleRequired: (account: string) => `账号“${account}”需要先选用包含局内房间工具的加工 Mod。`,
    completeRequired: "请先完成参与账号、快捷键和房间设置。",
    enablePromptTitle: "启用自动跟房",
    enablePromptDescription: "参与账号需要使用包含“局内房间工具”的 D2RHub 加工 Mod。你可以先去检查或加工 Mod，也可以在已经确认准备完成后继续启用。",
    checkModFirst: "先检查 Mod",
    continueEnable: "已准备好，继续启用",
    modRedirectHint: "请为参与账号确认或加工“局内房间工具”，完成后再返回启用自动跟房。",
    primary: "主账号",
    selectPrimary: "选择主账号",
    followers: "跟随账号",
    noAccounts: "没有可用的已初始化账号。请先在“账号与实例”完成初始化。",
    modeAndRoom: "运行方式与房间",
    manualMode: "手动跟随",
    manualModeHelp: "建房后等待手动确认。",
    automaticMode: "自动跟随",
    automaticModeHelp: "建房后按延时自动加入。",
    followerDelay: "建房后等待（秒）",
    followerJoinMode: "小号进房方式",
    simultaneousJoin: "同时进房",
    simultaneousJoinHelp: "所有可用小号同时派发进房指令。",
    intervalJoin: "间隔进房",
    intervalJoinHelp: "按设置顺序定时派发，不判断前一小号状态。",
    followerJoinInterval: "小号进房间隔（秒）",
    followerJoinIntervalHelp: "第一个立即派发；后续按固定间隔派发，互不等待。",
    followerJoinOrder: "间隔进房顺序",
    followerJoinOrderHelp: "窗口状态只记入日志，不会阻断或推迟后续账号。",
    moveFollowerUp: (account: string) => `将“${account}”提前一位`,
    moveFollowerDown: (account: string) => `将“${account}”后移一位`,
    createShortcut: "创建房间快捷键",
    followerShortcut: "跟随账号快捷键",
    shortcutCapture: "点击后按下组合键",
    shortcutRecording: "请按下组合键…",
    prefix: "房名开头",
    password: "房间密码",
    passwordOptional: "可选；留空则创建无密码房间。旧配置中的密码会继续保留。",
    roomNaming: "房间命名",
    roomNamingHelp: "前缀与序号组合生成下一局房名",
    sequence: "下一个序号",
    width: "序号位数",
    preview: "下次房名",
    roomActions: "房间操作",
    roomActionsHelp: "手动模式下可反复创建新房，再按需要让小号加入最后一次成功创建的房间。",
    startPrimary: "主账号创建房间",
    startFollowers: "让跟随账号加入",
    advanced: "高级输入时序",
    advancedHelp: "只有在机器负载较高或游戏大厅响应异常时才需要调整。",
    stepDelay: "步骤间隔（毫秒）",
    keyHold: "按住时间（毫秒）",
    inputTimingHelp: "后台模式使用整段粘贴，不再逐字输入。Ctrl 生效及 Tab 响应至少等待 120 毫秒；全选、粘贴的按住和释放后响应各至少等待 200 毫秒，步骤间隔更大时使用该值。普通导航及回车使用按住时间。",
    characterDelay: "松开间隔（毫秒）",
    backgroundStrategy: "后台按键投递",
    postKeys: "Windows 消息投递（推荐）",
    sendKeys: "同步窗口消息投递",
    primaryRequired: "启用前请选择主账号。",
    followersRequired: "启用前至少选择一个跟随账号。",
    duplicateParticipants: "同一账号不能同时作为主账号和跟随账号。",
    shortcutRequired: "启用前请设置两个快捷键。",
    shortcutInvalid: "快捷键格式无效；请点击输入框并直接按下组合键。",
    shortcutConflict: "创建和跟随快捷键不能相同。",
    invalidRoomText: "仅支持英文字母、数字、连字符和下划线。",
    roomTooLong: "房名和密码最多 15 个字符。",
    invalidSequence: "序号必须是 0–4294967295 的整数，位数应为 1–6。",
    invalidTiming: "建房后等待应为 0.5–60 秒，小号进房间隔应为 1–60 秒；后台步骤间隔 0–2000 毫秒、按住和松开间隔 10–250 毫秒。",
    accountUnavailable: "配置中包含已删除或尚未初始化的账号，请重新选择。",
    loadFailed: "无法读取自动跟房模块",
    saveFailed: "无法应用自动跟房配置",
    savedButRuntimeFailed: "配置已保存，但模块未能立即应用",
    actionFailed: "自动跟房操作失败",
  },
  "en-US": {
    enableLabel: "Enable",
    saveLaunchScheme: "Save launch scheme",
    retrySave: "Retry save",
    followTrigger: "Follow trigger",
    selectAllFollowers: "Select all",
    clearFollowers: "Clear",
    followersSelected: (count: number) => `${count} selected`,
    followerOrder: "Join order",
    backgroundMethodHelp: "Keep the primary in front. Create opens every participant's form and pastes the room name using physical Ctrl with background keys. Refresh all passwords on first use, changes, or new processes. The primary submits first; followers keep their forms until the join shortcut or automatic delay sends Enter only. Filling briefly takes control of input and the clipboard.",
    title: "Room Automation",
    subtitle: "Choose participants and room naming. Changes save automatically.",
    enabled: "Enable room automation",
    unavailable: "Module unavailable",
    loading: "Loading module status…",
    disabled: "Module off",
    disabledDescription: "Your configuration is kept, but shortcuts and room tasks do not run.",
    ready: "Module ready",
    error: "Task needs attention",
    apply: "Apply settings",
    applying: "Saving…",
    discard: "Discard",
    applied: "Settings applied",
    unsaved: "Unapplied changes",
    unsavedHelp: "Valid changes save automatically. Invalid edits stay on this page and do not change runtime settings.",
    staleHint: "Settings changed elsewhere. Reload before applying again.",
    retryLoad: "Reload",
    participants: "Participants",
    participantsHelp: "Choose the creator and the accounts that should join the same room.",
    participantCapsules: "Participant Mods",
    participantCapsulesHelp: "Choose a Mod for every participant; missing room tools can be added from here.",
    selectCapsule: "Choose Mod",
    prepareCapsule: "Process a Mod",
    capsuleReady: "In-game room tools ready",
    capsuleMissing: "No compatible Mod with room tools",
    capsulePoolLoading: "Loading available Mods…",
    capsulePoolUnavailable: "The available Mod list is unavailable",
    capsuleRequired: (account: string) => `Account “${account}” needs a processed Mod with In-game room tools.`,
    completeRequired: "Complete the participant, shortcut, and room settings first.",
    enablePromptTitle: "Enable room automation",
    enablePromptDescription: "Every participant needs a D2RHub-processed Mod containing In-game room tools. Check or process the Mods first, or continue if you have already verified them.",
    checkModFirst: "Check Mods first",
    continueEnable: "Already ready — enable",
    modRedirectHint: "Verify or add In-game room tools for each participant, then return to enable room automation.",
    primary: "Primary account",
    selectPrimary: "Select a primary account",
    followers: "Follower accounts",
    noAccounts: "No initialized accounts are available. Finish setup in Accounts & Instances first.",
    modeAndRoom: "Mode & room",
    manualMode: "Manual followers",
    manualModeHelp: "Wait for confirmation after creation.",
    automaticMode: "Automatic followers",
    automaticModeHelp: "Join automatically after the delay.",
    followerDelay: "Post-create wait (seconds)",
    followerJoinMode: "Follower join method",
    simultaneousJoin: "Join together",
    simultaneousJoinHelp: "Dispatch the join command to every available follower at once.",
    intervalJoin: "Staggered join",
    intervalJoinHelp: "Dispatch on a fixed schedule without judging the previous follower's state.",
    followerJoinInterval: "Follower join interval (seconds)",
    followerJoinIntervalHelp: "The first dispatch is immediate; later followers start at the fixed interval without waiting for one another.",
    followerJoinOrder: "Staggered join order",
    followerJoinOrderHelp: "Window state is logged only and never blocks or delays later accounts.",
    moveFollowerUp: (account: string) => `Move “${account}” earlier`,
    moveFollowerDown: (account: string) => `Move “${account}” later`,
    createShortcut: "Create-room shortcut",
    followerShortcut: "Join-followers shortcut",
    shortcutCapture: "Click, then press a key combination",
    shortcutRecording: "Press a key combination…",
    prefix: "Room prefix",
    password: "Room password",
    passwordOptional: "Optional. Leave empty for a public room; existing configured passwords are preserved.",
    roomNaming: "Room naming",
    roomNamingHelp: "The prefix and sequence form the next room name",
    sequence: "Next sequence",
    width: "Sequence width",
    preview: "Next room",
    roomActions: "Room actions",
    roomActionsHelp: "In manual mode you can create repeatedly, then join followers to the latest successful room.",
    startPrimary: "Create with primary",
    startFollowers: "Join followers",
    advanced: "Advanced input timing",
    advancedHelp: "Adjust only when a heavily loaded machine or game lobby responds unreliably.",
    stepDelay: "Step delay (ms)",
    keyHold: "Key hold duration (ms)",
    inputTimingHelp: "Background mode pastes whole fields. Allow at least 120 ms for Ctrl and Tab, and at least 200 ms during and after each select/paste chord; larger step delays take precedence. Navigation and Enter use the key hold duration.",
    characterDelay: "Key release interval (ms)",
    backgroundStrategy: "Background key delivery",
    postKeys: "Windows message delivery (recommended)",
    sendKeys: "Synchronous window messages",
    primaryRequired: "Choose a primary account before enabling.",
    followersRequired: "Choose at least one follower before enabling.",
    duplicateParticipants: "An account cannot be both primary and follower.",
    shortcutRequired: "Set both shortcuts before enabling.",
    shortcutInvalid: "Invalid shortcut. Click the field and press the combination directly.",
    shortcutConflict: "Create and follower shortcuts must differ.",
    invalidRoomText: "Use letters, numbers, hyphens, and underscores only.",
    roomTooLong: "Room names and passwords are limited to 15 characters.",
    invalidSequence: "Sequence must be an integer from 0 to 4294967295; width must be 1–6.",
    invalidTiming: "Post-create wait is 0.5–60s; follower interval is 1–60s. Background step delay: 0–2000ms; key hold/release: 10–250ms.",
    accountUnavailable: "The configuration references a deleted or uninitialized account. Select accounts again.",
    loadFailed: "Could not load room automation",
    saveFailed: "Could not apply room automation settings",
    savedButRuntimeFailed: "Settings were saved, but the module could not apply them immediately",
    actionFailed: "Room automation action failed",
  },
} as const satisfies Record<SettingsLanguage, object>;
