import type { SettingsLanguage } from "../settings/settingsRegistry";

export const ROOM_AUTOMATION_COPY = {
  "zh-CN": {
    enableLabel: "启用",
    saveLaunchScheme: "保存启动方案",
    retrySave: "重试保存",
    followTrigger: "跟随触发",
    backgroundMethodShort: "后台按键",
    foregroundMethodShort: "前台键鼠",
    foregroundMethodSummary: "依次切到游戏窗口操作，所有可用小号流程完成后自动切回主号。请从局内开始，显示工具栏并使用 16:9 高清键鼠界面；无需绑定聊天键。",
    selectAllFollowers: "全选",
    clearFollowers: "清空",
    followersSelected: (count: number) => `已选 ${count} 个`,
    followerOrder: "进房顺序",
    timingStepInterval: "操作之间的间隔（毫秒）",
    timingWindowFocus: "切到前台执行时间（毫秒）",
    timingMouseHold: "点击按住时间（毫秒）",
    timingFormResponse: "开表单响应（鼠标抬起后，毫秒）",
    timingFocusResponse: "点击 / Tab / 难度切换响应（毫秒）",
    timingSelectResponse: "Ctrl+A 全选响应（毫秒）",
    timingPasteResponse: "Ctrl+V 粘贴响应（毫秒）",
    timingChordHold: "Ctrl+A / Ctrl+V / Tab 按住（毫秒）",
    timingSubmitHold: "回车按住时间（毫秒）",
    inputMethod: "建房 / 入房操作方案",
    backgroundMethod: "方案一：后台按键（原方案）",
    foregroundMethod: "方案二：前台键鼠接管",
    backgroundMethodHelp: "使用后台窗口消息与已绑定的聊天键填写表单。",
    foregroundMethodHelp: "主号和小号均切到前台，点击局内工具栏和输入框，以物理 Ctrl+V 粘贴。每项操作先保留自己的按住或响应时间，再等待独立的步骤间隔；可在高级时序中分别调整。无需聊天键绑定或重新加工 Mod；请显示工具栏，使用 16:9 高清键鼠界面，并从局内开始。密码在每个进程首次填写或变化时粘贴，主号首次选择地狱。",
    sequentialJoin: "依次进房",
    foregroundQueueHelp: "按账号顺序完成键鼠操作，再切到下一个窗口；失败时停止，避免继续误操作。",
    foregroundIntervalHelp: "按顺序接管；相邻开始时间至少间隔指定秒数，且等待前一个窗口输入完成。",
    foregroundTimingHelp: "主号、小号共用这一套时序和字段操作：点击房名 → 全选粘贴 → Tab 切密码 → 全选粘贴。默认鼠标抬起后等表单响应 150 毫秒，点击 / Tab 后等焦点 100 毫秒，全选后等 100 毫秒，粘贴后等 100 毫秒；响应时间不扣除按住或鼠标移动耗时。组合键与 Tab 按住 50 毫秒，每项响应后另加步骤间隔。回车按住 20 毫秒后立即继续。密码仍只在进程首次填写或变化时更新；仅创建流程首次额外选择地狱。",
    title: "自动跟房",
    subtitle: "设置主号、跟随账号和房名规则；修改会自动保存。",
    enabled: "启用自动跟房模块",
    unavailable: "模块不可用",
    loading: "正在读取模块状态…",
    disabled: "模块已停用",
    disabledDescription: "配置会保留，但快捷键和跟房任务均不会运行。",
    ready: "模块已就绪",
    error: "任务需要处理",
    apply: "应用配置",
    applying: "正在保存…",
    discard: "放弃更改",
    applied: "配置已应用",
    unsaved: "有未保存的修改",
    unsavedHelp: "有效修改会自动保存；校验未通过的内容会保留在本页，不会更新运行参数。",
    staleHint: "配置已被其他操作更新，请重新载入后再应用。",
    retryLoad: "重新载入",
    participants: "参与账号",
    participantsHelp: "指定创建者与需要加入同一房间的账号。",
    participantCapsules: "参与账号 Mod",
    participantCapsulesHelp: "主号和小号分别选择需要使用的 Mod；缺少房间工具时会引导加工。",
    selectCapsule: "选择 Mod",
    prepareCapsule: "前往加工",
    capsuleReady: "局内房间工具已就绪",
    capsuleMissing: "缺少可用的局内房间工具",
    capsulePoolLoading: "正在读取可用 Mod，请稍候。",
    capsulePoolUnavailable: "无法读取可用 Mod 列表",
    capsuleRequired: (account: string) => `账号“${account}”需要先选用包含局内房间工具的加工 Mod。`,
    completeRequired: "请先完成参与账号、快捷键和房间设置。",
    enablePromptTitle: "启用自动跟房",
    enablePromptDescription: "参与账号需要使用包含“局内房间工具”的 D2RHub 加工 Mod。你可以先去检查或加工 Mod，也可以在已经确认准备完成后继续启用。",
    checkModFirst: "先检查 Mod",
    continueEnable: "已准备好，继续启用",
    modRedirectHint: "请为参与账号确认或加工“局内房间工具”，完成后再返回启用自动跟房。",
    primary: "主账号",
    selectPrimary: "选择主账号",
    followers: "跟随账号",
    noAccounts: "没有可用的已初始化账号。请先在“账号与实例”完成初始化。",
    modeAndRoom: "运行方式与房间",
    manualMode: "手动跟随",
    manualModeHelp: "建房后等待手动确认。",
    automaticMode: "自动跟随",
    automaticModeHelp: "建房后按延时自动加入。",
    followerDelay: "建房后等待（秒）",
    followerJoinMode: "小号进房方式",
    simultaneousJoin: "同时进房",
    simultaneousJoinHelp: "所有可用小号同时派发进房指令。",
    intervalJoin: "间隔进房",
    intervalJoinHelp: "按设置顺序定时派发，不判断前一小号状态。",
    followerJoinInterval: "小号进房间隔（秒）",
    followerJoinIntervalHelp: "第一个立即派发；后续按固定间隔派发，互不等待。",
    followerJoinOrder: "间隔进房顺序",
    followerJoinOrderHelp: "窗口状态只记入日志，不会阻断或推迟后续账号。",
    moveFollowerUp: (account: string) => `将“${account}”提前一位`,
    moveFollowerDown: (account: string) => `将“${account}”后移一位`,
    createShortcut: "创建房间快捷键",
    followerShortcut: "跟随账号快捷键",
    shortcutCapture: "点击后按下组合键",
    shortcutRecording: "请按下组合键…",
    prefix: "房名开头",
    password: "房间密码",
    passwordOptional: "可选；留空则创建无密码房间。旧配置中的密码会继续保留。",
    roomNaming: "房间命名",
    roomNamingHelp: "前缀与序号组合生成下一局房名",
    sequence: "下一个序号",
    width: "序号位数",
    preview: "下次房名",
    roomActions: "房间操作",
    roomActionsHelp: "手动模式下可反复创建新房，再按需要让小号加入最后一次成功创建的房间。",
    startPrimary: "主账号创建房间",
    startFollowers: "让跟随账号加入",
    f13Title: "游戏聊天键绑定",
    chatKey: "聊天按键",
    pauseKey: "Pause（默认）",
    f13Description: "默认用 Pause 打开聊天输入，也可选择 F13。直接覆盖兼容角色键位文件中的第二个“聊天”快捷键，第一快捷键无需为回车；发送端同步使用所选按键。每个文件保留首次备份，恢复时只还原聊天第二快捷键。",
    f13Consent: "启用后，每次自动跟房配置变更会扫描一次，切换聊天键也会立即扫描。扫描包括系统存档目录，以及对应游戏安装目录（Mod 管理打开的位置）下 mods/Mod名字 中的 .keyo；同名文件取修改时间最新的完整键位配置，更新聊天第二快捷键后同步至系统目录和已有的 Mod 副本。时间相同优先系统目录，其次按 Mod 目录名排序。文件不会被持续监视。",
    newCharacterScanHint: "新建角色后，点击“扫描并更新绑定”，将兼容角色的聊天第二快捷键更新为当前选择。游戏运行期间也可扫描，更改在游戏下次启动时生效。",
    f13LegacyNotice: "旧版配置中的自动授权已被撤销。请阅读说明后重新确认。",
    bindingReady: "聊天键绑定已就绪",
    bindingReadySummary: "聊天键已就绪；新建角色后请手动扫描",
    bindingNotReady: "聊天键绑定尚未就绪",
    bindingUnavailable: "无法读取 聊天键绑定状态",
    bindingLoading: "正在读取 聊天键绑定状态…",
    retryBinding: "重试读取",
    refreshBinding: "刷新状态",
    bindingRequired: "需要扫描 聊天键绑定",
    bindingFiles: (installed: number, total: number) => `${installed}/${total} 个按键文件已安装`,
    bindingConflicts: (count: number) => `${count} 个文件存在按键冲突，未自动修改`,
    bindingOrphans: (count: number) => `保留 ${count} 个已删除角色的历史备份，不影响当前角色`,
    configScanActive: "配置变更时扫描",
    scanAndInstallBinding: "扫描并更新绑定",
    manualScanComplete: (installed: number, total: number, d2rRunning: boolean) => `扫描完成：${installed}/${total} 个按键文件已安装${d2rRunning ? "；更改在游戏下次启动时生效" : ""}`,
    configScanComplete: "配置已保存，并执行了一次聊天键扫描。",
    gameRunningHint: "D2R 正在运行，仍可扫描更新绑定，更改在游戏下次启动时生效。切换聊天按键或恢复原始绑定前，请先关闭所有 D2R。",
    restoreBinding: "恢复原始按键绑定",
    advanced: "高级输入时序",
    advancedHelp: "只有在机器负载较高或游戏大厅响应异常时才需要调整。",
    stepDelay: "步骤间隔（毫秒）",
    keyHold: "按住时间（毫秒）",
    inputTimingHelp: "步骤间隔和按住时间默认均为 50 毫秒，松开间隔用于字符和退格。开表单后、切换输入框后各额外等待固定 50 毫秒。",
    characterDelay: "松开间隔（毫秒）",
    backgroundStrategy: "后台文本投递",
    postKeys: "Windows 消息投递（推荐）",
    sendKeys: "同步窗口消息投递",
    primaryRequired: "启用前请选择主账号。",
    followersRequired: "启用前至少选择一个跟随账号。",
    duplicateParticipants: "同一账号不能同时作为主账号和跟随账号。",
    shortcutRequired: "启用前请设置两个快捷键。",
    shortcutInvalid: "快捷键格式无效；请点击输入框并直接按下组合键。",
    shortcutConflict: "创建和跟随快捷键不能相同。",
    invalidRoomText: "仅支持英文字母、数字、连字符和下划线。",
    roomTooLong: "房名和密码最多 15 个字符。",
    invalidSequence: "序号必须是 0–4294967295 的整数，位数应为 1–6。",
    invalidTiming: "建房后等待应为 2–60 秒，小号进房间隔应为 1–60 秒；后台步骤间隔 0–2000 毫秒、按住和松开间隔 10–250 毫秒；鼠标接管的各操作时长 1–2000 毫秒、操作间隔 0–2000 毫秒。",
    accountUnavailable: "配置中包含已删除或尚未初始化的账号，请重新选择。",
    loadFailed: "无法读取自动跟房模块",
    saveFailed: "无法应用自动跟房配置",
    savedButRuntimeFailed: "配置已保存，但模块未能立即应用",
    actionFailed: "自动跟房操作失败",
    bindingFailed: "无法扫描或更新聊天键绑定",
  },
  "en-US": {
    enableLabel: "Enable",
    saveLaunchScheme: "Save launch scheme",
    retrySave: "Retry save",
    followTrigger: "Follow trigger",
    backgroundMethodShort: "Background keys",
    foregroundMethodShort: "Mouse & keyboard",
    foregroundMethodSummary: "Operates each game window in the foreground, then returns focus to the primary after all available followers finish. Start in-game with the toolbar visible and the 16:9 HD keyboard/mouse UI. No chat binding needed.",
    selectAllFollowers: "Select all",
    clearFollowers: "Clear",
    followersSelected: (count: number) => `${count} selected`,
    followerOrder: "Join order",
    timingStepInterval: "Interval between operations (ms)",
    timingWindowFocus: "Window focus duration (ms)",
    timingMouseHold: "Mouse button hold (ms)",
    timingFormResponse: "Form response after mouse-up (ms)",
    timingFocusResponse: "Click / Tab / difficulty response (ms)",
    timingSelectResponse: "Ctrl+A selection response (ms)",
    timingPasteResponse: "Ctrl+V paste response (ms)",
    timingChordHold: "Ctrl+A / Ctrl+V / Tab hold (ms)",
    timingSubmitHold: "Enter hold (ms)",
    inputMethod: "Create / join input method",
    backgroundMethod: "Method 1: Background keys (original)",
    foregroundMethod: "Method 2: Foreground mouse and keyboard",
    backgroundMethodHelp: "Fill forms using background window messages and the configured chat key.",
    foregroundMethodHelp: "Focus both primary and follower games, click the in-game toolbar and fields, and paste with physical Ctrl+V. Give each operation its own hold or response time, followed by a separate interval; adjust these independently under advanced timing. No chat binding or Mod rebuild is required. Show the toolbar, use the 16:9 HD keyboard/mouse interface, and start in a game. Passwords are entered on first use per process or when changed; the primary selects Hell on first use.",
    sequentialJoin: "Join in sequence",
    foregroundQueueHelp: "Finish each account's input before focusing the next window. Stop on failure to avoid further unintended input.",
    foregroundIntervalHelp: "Use account order, wait at least the configured interval between starts, and finish the previous window's input first.",
    foregroundTimingHelp: "Primary and followers share one timing profile and field sequence: click name → select/paste → Tab to password → select/paste. Defaults: wait 150 ms after form-opening mouse-up, 100 ms after click/Tab, 100 ms after selection, and 100 ms after paste. Response windows exclude cursor movement and key holds. Chords and Tab are held for 50 ms, followed by the configured interval after each response. Release Enter after 20 ms and continue immediately. Passwords are updated on first use per process or when changed; only creation additionally selects Hell on first use.",
    title: "Room Automation",
    subtitle: "Choose participants and room naming. Changes save automatically.",
    enabled: "Enable room automation",
    unavailable: "Module unavailable",
    loading: "Loading module status…",
    disabled: "Module off",
    disabledDescription: "Your configuration is kept, but shortcuts and room tasks do not run.",
    ready: "Module ready",
    error: "Task needs attention",
    apply: "Apply settings",
    applying: "Saving…",
    discard: "Discard",
    applied: "Settings applied",
    unsaved: "Unapplied changes",
    unsavedHelp: "Valid changes save automatically. Invalid edits stay on this page and do not change runtime settings.",
    staleHint: "Settings changed elsewhere. Reload before applying again.",
    retryLoad: "Reload",
    participants: "Participants",
    participantsHelp: "Choose the creator and the accounts that should join the same room.",
    participantCapsules: "Participant Mods",
    participantCapsulesHelp: "Choose a Mod for every participant; missing room tools can be added from here.",
    selectCapsule: "Choose Mod",
    prepareCapsule: "Process a Mod",
    capsuleReady: "In-game room tools ready",
    capsuleMissing: "No compatible Mod with room tools",
    capsulePoolLoading: "Loading available Mods…",
    capsulePoolUnavailable: "The available Mod list is unavailable",
    capsuleRequired: (account: string) => `Account “${account}” needs a processed Mod with In-game room tools.`,
    completeRequired: "Complete the participant, shortcut, and room settings first.",
    enablePromptTitle: "Enable room automation",
    enablePromptDescription: "Every participant needs a D2RHub-processed Mod containing In-game room tools. Check or process the Mods first, or continue if you have already verified them.",
    checkModFirst: "Check Mods first",
    continueEnable: "Already ready — enable",
    modRedirectHint: "Verify or add In-game room tools for each participant, then return to enable room automation.",
    primary: "Primary account",
    selectPrimary: "Select a primary account",
    followers: "Follower accounts",
    noAccounts: "No initialized accounts are available. Finish setup in Accounts & Instances first.",
    modeAndRoom: "Mode & room",
    manualMode: "Manual followers",
    manualModeHelp: "Wait for confirmation after creation.",
    automaticMode: "Automatic followers",
    automaticModeHelp: "Join automatically after the delay.",
    followerDelay: "Post-create wait (seconds)",
    followerJoinMode: "Follower join method",
    simultaneousJoin: "Join together",
    simultaneousJoinHelp: "Dispatch the join command to every available follower at once.",
    intervalJoin: "Staggered join",
    intervalJoinHelp: "Dispatch on a fixed schedule without judging the previous follower's state.",
    followerJoinInterval: "Follower join interval (seconds)",
    followerJoinIntervalHelp: "The first dispatch is immediate; later followers start at the fixed interval without waiting for one another.",
    followerJoinOrder: "Staggered join order",
    followerJoinOrderHelp: "Window state is logged only and never blocks or delays later accounts.",
    moveFollowerUp: (account: string) => `Move “${account}” earlier`,
    moveFollowerDown: (account: string) => `Move “${account}” later`,
    createShortcut: "Create-room shortcut",
    followerShortcut: "Join-followers shortcut",
    shortcutCapture: "Click, then press a key combination",
    shortcutRecording: "Press a key combination…",
    prefix: "Room prefix",
    password: "Room password",
    passwordOptional: "Optional. Leave empty for a public room; existing configured passwords are preserved.",
    roomNaming: "Room naming",
    roomNamingHelp: "The prefix and sequence form the next room name",
    sequence: "Next sequence",
    width: "Sequence width",
    preview: "Next room",
    roomActions: "Room actions",
    roomActionsHelp: "In manual mode you can create repeatedly, then join followers to the latest successful room.",
    startPrimary: "Create with primary",
    startFollowers: "Join followers",
    f13Title: "In-game chat binding",
    chatKey: "Chat key",
    pauseKey: "Pause (default)",
    f13Description: "Pause opens chat by default; F13 is also available. The secondary Chat binding is overwritten in compatible key files; the primary binding does not need to be Enter. Input delivery uses the selected key. Each file retains its first backup; restoration only restores the secondary Chat binding.",
    f13Consent: "Each configuration change, including changing the chat key, runs one scan while enabled. Scans include .keyo files in the system save directory and the corresponding game installation's mods/ModName folders, as opened by Mod management. For matching names, the newest complete key configuration is selected, its secondary Chat binding is updated, and it is synced to the system directory and existing Mod copies. Equal timestamps prefer the system copy, then Mod directory name order. Files are not watched continuously.",
    newCharacterScanHint: "After creating a character, select Scan & update bindings to apply the selected secondary Chat key. You can scan while D2R is running; changes take effect the next time the game starts.",
    f13LegacyNotice: "Implicit authorization from an older configuration was revoked. Review this notice and consent again.",
    bindingReady: "Chat binding ready",
    bindingReadySummary: "Chat binding is ready; scan manually after creating a character",
    bindingNotReady: "Chat binding not ready",
    bindingUnavailable: "Could not read the chat binding status",
    bindingLoading: "Loading chat binding status…",
    retryBinding: "Retry status",
    refreshBinding: "Refresh status",
    bindingRequired: "Chat binding needs a scan",
    bindingFiles: (installed: number, total: number) => `${installed}/${total} key files installed`,
    bindingConflicts: (count: number) => `${count} files have key conflicts and were not changed`,
    bindingOrphans: (count: number) => `${count} backups for removed characters are retained and do not block current characters`,
    configScanActive: "Scans on configuration changes",
    scanAndInstallBinding: "Scan & update bindings",
    manualScanComplete: (installed: number, total: number, d2rRunning: boolean) => `Scan complete: ${installed}/${total} key files installed${d2rRunning ? "; changes take effect the next time the game starts" : ""}`,
    configScanComplete: "Settings saved and one chat binding scan completed.",
    gameRunningHint: "D2R is running. You can scan and update bindings; changes take effect the next time the game starts. Close every D2R process before switching the chat key or restoring the original binding.",
    restoreBinding: "Restore original binding",
    advanced: "Advanced input timing",
    advancedHelp: "Adjust only when a heavily loaded machine or game lobby responds unreliably.",
    stepDelay: "Step delay (ms)",
    keyHold: "Key hold duration (ms)",
    inputTimingHelp: "Step delay and key hold duration both default to 50 ms. The release interval applies to characters and Backspace. Opening the form and switching fields each add a fixed 50 ms wait.",
    characterDelay: "Key release interval (ms)",
    backgroundStrategy: "Background text delivery",
    postKeys: "Windows message delivery (recommended)",
    sendKeys: "Synchronous window messages",
    primaryRequired: "Choose a primary account before enabling.",
    followersRequired: "Choose at least one follower before enabling.",
    duplicateParticipants: "An account cannot be both primary and follower.",
    shortcutRequired: "Set both shortcuts before enabling.",
    shortcutInvalid: "Invalid shortcut. Click the field and press the combination directly.",
    shortcutConflict: "Create and follower shortcuts must differ.",
    invalidRoomText: "Use letters, numbers, hyphens, and underscores only.",
    roomTooLong: "Room names and passwords are limited to 15 characters.",
    invalidSequence: "Sequence must be an integer from 0 to 4294967295; width must be 1–6.",
    invalidTiming: "Post-create wait is 2–60s; follower interval is 1–60s. Background step delay: 0–2000ms; key hold/release: 10–250ms. Mouse takeover operation durations: 1–2000ms; operation interval: 0–2000ms.",
    accountUnavailable: "The configuration references a deleted or uninitialized account. Select accounts again.",
    loadFailed: "Could not load room automation",
    saveFailed: "Could not apply room automation settings",
    savedButRuntimeFailed: "Settings were saved, but the module could not apply them immediately",
    actionFailed: "Room automation action failed",
    bindingFailed: "Could not scan or update the chat binding",
  },
} as const satisfies Record<SettingsLanguage, object>;
